---
AWSTemplateFormatVersion: '2010-09-09'
Description: Kubernetes IAM Instance Profiles
Resources:
  MasterInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: MasterInstanceRole
  MasterInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: master
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: K8sMasterDescribeResources
            Effect: Allow
            Action:
            - ec2:DescribeInstances
            - ec2:DescribeRegions
            - ec2:DescribeRouteTables
            - ec2:DescribeSecurityGroups
            - ec2:DescribeSubnets
            - ec2:DescribeVolumes
            Resource: "*"
          - Sid: K8sMasterAllResourcesWriteable
            Effect: Allow
            Action:
            - ec2:CreateRoute
            - ec2:CreateSecurityGroup
            - ec2:CreateTags
            - ec2:CreateVolume
            - ec2:ModifyInstanceAttribute
            Resource: "*"
          - Sid: K8sMasterTaggedResourcesWritable
            Effect: Allow
            Action:
            - ec2:AttachVolume
            - ec2:AuthorizeSecurityGroupIngress
            - ec2:DeleteRoute
            - ec2:DeleteSecurityGroup
            - ec2:DeleteVolume
            - ec2:DetachVolume
            - ec2:RevokeSecurityGroupIngress
            Resource: "*"
      - PolicyName: ecr
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: K8sECR
            Effect: Allow
            Action:
            - ecr:GetAuthorizationToken
            - ecr:BatchCheckLayerAvailability
            - ecr:GetDownloadUrlForLayer
            - ecr:GetRepositoryPolicy
            - ecr:DescribeRepositories
            - ecr:ListImages
            - ecr:BatchGetImage
            Resource: "*"
      - PolicyName: cni
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: K8sNodeAwsVpcCNI
            Effect: Allow
            Action:
            - ec2:CreateNetworkInterface
            - ec2:AttachNetworkInterface
            - ec2:DeleteNetworkInterface
            - ec2:DetachNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DescribeInstances
            - ec2:ModifyNetworkInterfaceAttribute
            - ec2:AssignPrivateIpAddresses
            - tag:TagResources
            Resource: "*"
      - PolicyName: autoscaler
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: K8sClusterAutoscaler
            Effect: Allow
            Action:
            - autoscaling:DescribeAutoScalingGroups
            - autoscaling:DescribeAutoScalingInstances
            - autoscaling:DescribeTags
            - autoscaling:DescribeLaunchConfigurations
            - autoscaling:SetDesiredCapacity
            - autoscaling:TerminateInstanceInAutoScalingGroup
            Resource: "*"
  NodeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: NodeInstanceRole
  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: node
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: K8sNodeDescribeResources
            Effect: Allow
            Action:
            - ec2:DescribeInstances
            - ec2:DescribeRegions
            Resource: "*"
      - PolicyName: ecr
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: K8sECR
            Effect: Allow
            Action:
            - ecr:GetAuthorizationToken
            - ecr:BatchCheckLayerAvailability
            - ecr:GetDownloadUrlForLayer
            - ecr:GetRepositoryPolicy
            - ecr:DescribeRepositories
            - ecr:ListImages
            - ecr:BatchGetImage
            Resource: "*"
      - PolicyName: cni
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: K8sNodeAwsVpcCNI
            Effect: Allow
            Action:
            - ec2:CreateNetworkInterface
            - ec2:AttachNetworkInterface
            - ec2:DeleteNetworkInterface
            - ec2:DetachNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DescribeInstances
            - ec2:ModifyNetworkInterfaceAttribute
            - ec2:AssignPrivateIpAddresses
            - tag:TagResources
            Resource: "*"
Outputs:
  MasterInstanceProfileArn:
    Description: Kubernetes Master instance profile
    Value:
      Fn::GetAtt:
      - MasterInstanceProfile
      - Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-MasterInstanceProfileArn"
  NodeInstanceProfileArn:
    Description: Kubernetes Node instance profile
    Value:
      Fn::GetAtt:
      - NodeInstanceProfile
      - Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-NodeInstanceProfileArn"
